branch-defaults:
  dev:
    environment: udagram-ibra-dev-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udagram-ibra-dev
  branch: null
  default_ec2_keyname: Paris
  default_platform: Node.js
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: udacity
  repository: null
  sc: git
  workspace_type: Application
